### ISSUE TITLE
Little Snitch Package recipe fails

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/smithjw-recipes#12]
Hi 

The current Little Snitch recipe fails as both the location of the support files has changed with the v5.x release and where the system installs these on disk has changed.

I'm looking into this now but I suspect its more self contained and it should just be a case of deploying the App to /Applications and letting users go through the initial setup.

I'll see what I can find

**Comment by smithjw** [comment]
@Daz-wallace I haven't used Little Snitch for a couple of years now but let me know what you find. IIRC it was a pain to make this recipe in the first place because of the Installer Application rather than a traditional PKG. I ended up capturing where everything was deployed via Composer 😅

**Comment by Daz-wallace** [comment]
@smithjw Haha that's what I'm doing now to see what moves.

If it's radically different, I might create a new set for "Little Snitch 5", as we're only looking for the v5 version 😊

**Comment by smithjw** [comment]
Sounds good! I might update this recipe to state it may no longer work and point to yours when you're done

**Comment by Daz-wallace** [comment]
My VM is struggling to capture what I need so I'll need to come back to this. I'll keep you posted

**Comment by Daz-wallace** [comment]
Hi @smithjw 

So It does look like Little Snitch 5 is more self contained. With the right SEXT profile in place there's still a 'setup' wizard you'll need to follow but it shouldn't need any admins rights.

It's your call but we can either spawn off a Little Snitch v5 recipes, or I can put in a PR to simplify the .pkg recipe you have, and set the minimum OS to macOS 11+

Lemmie know if you have a preference 😊

**Comment by smithjw** [comment]
Hmmm, thought I replied to this. If you create the pull request, I'm happy to test and merge it in :)

**Comment by smithjw** [comment]
This is resolved by https://github.com/autopkg/smithjw-recipes/pull/13
