### ISSUE TITLE
LogiOptions download url for URLTextSearcher has changed

### ISSUE THREAD

**Issue by eithor** [autopkg/smithjw-recipes#27]
Logitech has changed the url for the webpage listing downloads for LogiOptions. Please change https://www.logitech.com/product/options to https://www.logitech.com/en-us/software/options.html

**Comment by smithjw** [comment]
Hey @eithor, I'm deprecating my pkg and download recipes in favour of [com.github.wegotoeleven-recipes.pkg.LogiOptionsPlus](https://github.com/autopkg/wegotoeleven-recipes/tree/main/Logitech). I'll have a new Jamf recipe here that uses them as a parent if that's what you're after too
