### ISSUE TITLE
DisplayLink Manager download recipe failing

### ISSUE THREAD

**Issue by jelockwood** [autopkg/smithjw-recipes#28]
I have been previously successfully using a combination of the DisplayLink Manager download recipe provided here https://github.com/autopkg/smithjw-recipes/blob/master/DisplayLink/DisplayLink_Manager.download.recipe.yaml along with a matching Munki recipe provided in the DataJar repo here https://github.com/autopkg/dataJAR-recipes/blob/master/DisplayLink%20Manager/DisplayLink%20Manager.munki.recipe 

Unfortunately for about the last week this has been failing and the further testing I have done suggests the failure is in the download recipe and not the munki recipe. 

When I run _only_ the download recipe it downloads a pkg file which is the current pkg file on the Synaptics website but it seems your recipe is expecting the download to be a DMG and tries and fails to process it on that basis.

I would therefore be grateful if @smithjw could look in to this.

As a related topic, it would also be useful if an option could be provided to ignore alpha and beta versions and only download stable release versions. (The 'latest' version on their website is labelled an Alpha release.)

**Comment by smithjw** [comment]
@jelockwood Ahh, I think I know what the issue is here. I've recently updated my download recipe to download both the original pkg and the login window pkg.

These are now combined in my pkg recipe

https://github.com/autopkg/dataJAR-recipes/issues/252#issuecomment-1266127740
