### ISSUE TITLE
Recipes use variable templating in input paths

### ISSUE THREAD

**Issue by fuzzylogiq** [autopkg/smithjw-recipes#33]
Hi, I was recently steered towards using your Docker recipes as the chilcote ones have been deprecated. However there is an issue with Docker.pkg.recipe.yaml (this is the only one I'm particularly bothered by, but I think it appears elsewhere in the repo too)

https://github.com/autopkg/smithjw-recipes/blob/07b22503e9cc0340a9d9d252208aa700fe9b83b7/Docker/Docker.pkg.recipe.yaml#L19-L20

The lines above use the variable %NAME% to copy the Docker app from a dmg into a pkgroot. However, this breaks if I change the variable %NAME% to anything other than "Docker" and is considered bad practice. You're actually _expecting_ the app to be called Docker.app so you shouldn't template it out in a way that a user could break the recipe.

I've opened a PR for this file to get our overrides working, but like I say, I don't think the problem is limited to just this recipe.

**Comment by smithjw** [comment]
Resolved in https://github.com/autopkg/smithjw-recipes/pull/34
