### ISSUE TITLE
Docker recipes issues

### ISSUE THREAD

**Issue by fuzzylogiq** [autopkg/smithjw-recipes#35]
Hi me again :)

Uncovered a couple of other issues with the Docker recipes...

* x64 is not an architecture that munki understands, should be x86_64 or arm64 in the Input of Docker.download.recipe, if you're then going to substitute it into the `supported_architectures` key of the munki pkginfo https://github.com/autopkg/smithjw-recipes/blob/849955822c69b5ef28685f47662cdd9348173d96/Docker/Docker.download.recipe.yaml#L13
* `supported_architectures` is an array of strings, your yaml has it as just one string below the key https://github.com/autopkg/smithjw-recipes/blob/849955822c69b5ef28685f47662cdd9348173d96/Docker/Docker.munki.recipe.yaml#L18
* Docker.munki.recipe is importing `%pathname%` instead of `%pkg_path%` so it's importing the dmg rather than the pkg, and we're not getting the postinstall script at all this way. https://github.com/autopkg/smithjw-recipes/blob/849955822c69b5ef28685f47662cdd9348173d96/Docker/Docker.munki.recipe.yaml#L23

I'll knock up a quick PR for you to look at

Thanks!

**Comment by fuzzylogiq** [comment]
Bump?

**Comment by smithjw** [comment]
Resolved with #36
