### ISSUE TITLE
ZoomIT jss does not work

### ISSUE THREAD

**Issue by beatlemike** [autopkg/smithjw-recipes#7]
Package has changed and the location of info.plist is no longer :"...AutoPkg/Cache/local.jss.ZoomIT/payload/Contents/Info.plist"

It now is found at:
"...AutoPkg/Cache/local.jss.ZoomIT/unpack/zoom.us.app/Contents/Info.plist "

**Comment by rtrouton** [comment]
Opened PR [https://github.com/autopkg/smithjw-recipes/pull/8](https://github.com/autopkg/smithjw-recipes/pull/8) to address this problem.
